-- Import Hisnul Mouslim cours 1 (révision): 50 questions "Introduction et importance du dhikr" depuis hisn1.json.
-- tenant Abou Abdelwahab (qawaid.abouabdelwahab.com). Remplace le contenu de cours 1.
-- À exécuter une seule fois.

do $$ declare t uuid:='6badf254-27a3-4f69-98e3-e67caa917371'; c uuid;
begin
  select id into c from quiz_courses where tenant_id=t and subject='Hisnul Mouslim' and number=1;
  if c is null then
    insert into quiz_courses(tenant_id,subject,number,title,position)
      values (t,'Hisnul Mouslim',1,'Introduction et importance du dhikr',1) returning id into c;
  else
    update quiz_courses set title='Introduction et importance du dhikr' where id=c;
    delete from quiz_questions where course_id=c;
  end if;
  insert into quiz_questions(tenant_id,course_id,difficulte,question,options,correct_index,justification,position) values
   (t,c,'moyenne','Comment s''appelle l''ouvrage étudié dans ce séminaire, et comment est-il traduit en français ?','["Al-Adhkâr – La Prairie des vertueux","Husn al-Muslim – La Citadelle du musulman","Al-Wâbil as-Sayyib – La pluie bienfaisante","Fiqh al-Ad''iya – La compréhension des invocations"]'::jsonb,1,'« Il sera étudié l''explication et le commentaire de Husn al-Muslim (Traduit en français par La Citadelle du musulman), un recueil d''invocations et d''évocations tirées du Coran et de la Sunna, rédigé par le docteur Sa''îd ibn ''Alî ibn Wahf al-Qahtânî. »',1),
   (t,c,'moyenne','Qui est l''auteur de Husn al-Muslim ?','["L''imam an-Nawawî","Ibn al-Qayyim","Sa''îd ibn ''Alî ibn Wahf al-Qahtânî","''Abd ar-Razzâq al-Badr"]'::jsonb,2,'« L''auteur, Sa''îd ibn ''Alî ibn Wahf al-Qahtânî, a obtenu un doctorat en sciences islamiques à l''université de Riyad. »',2),
   (t,c,'moyenne','L''auteur de Husn al-Muslim a été l''élève du Cheikh Ibn Bâz pendant environ vingt ans.','["Vrai","Faux"]'::jsonb,0,'« Il a également été un élève du Cheikh Ibn Bâz pendant près de vingt ans, comme mentionné dans sa biographie. »',3),
   (t,c,'moyenne','Quelle est l''année du décès de l''auteur Sa''îd al-Qahtânî ?','["2005","2012","2018","2023"]'::jsonb,2,'« Il est décédé en 2018 et a laissé derrière lui plusieurs ouvrages bénéfiques, dont Husn al-Muslim. »',4),
   (t,c,'moyenne','Parmi les ouvrages étudiés par l''auteur auprès du Cheikh Ibn Bâz figure le Tafsîr d''Ibn Kathîr.','["Vrai","Faux"]'::jsonb,0,'« Il a étudié auprès de lui de nombreux ouvrages fondamentaux, parmi lesquels les six recueils de hadith, le Musnad de l''imam Ahmad, le Muwatta'' de l''imam Mâlik, les Sunan de l''imam ad-Dârimî, le Tafsîr d''Ibn Kathîr. »',5),
   (t,c,'moyenne','Le livre contemporain conseillé par le cheikh sur les invocations est celui d''''Abd ar-Razzâq al-Badr, intitulé Fiqh al-Ad''iya wa-l-Adhkâr.','["Vrai","Faux"]'::jsonb,0,'« Parmi les livres contemporains que le cheikh conseille figure celui de ''Abd ar-Razzâq al-Badr, Fiqh al-Ad''iya wa-l-Adhkâr (« La compréhension des invocations et des rappels »). »',6),
   (t,c,'moyenne','Pour qu''une œuvre soit acceptée auprès d''Allah, elle doit réunir deux conditions. Lesquelles ?','["La connaissance et la pratique","La sincérité envers Allah et la conformité à la Sunna du Prophète ﷺ","La prière et le jeûne","La repentance et la patience"]'::jsonb,1,'« La base de l''adoration est que toute œuvre n''est acceptée auprès d''Allah سبحانه وتعالى que si elle réunit : la sincérité envers Allah et la conformité à la Sunna du Prophète ﷺ. »',7),
   (t,c,'moyenne','Quel verset de la sourate adh-Dhâriyât est cité dans le cours pour rappeler la finalité de la création ?','["« Et il se rappelle de toi en tout temps. » (v.50)","« Je n''ai créé les djinns et les hommes que pour qu''ils M''adorent. » (v.56)","« Et évoquez Allah abondamment pour que vous réussissiez. » (v.10)","« Évoquez Allah debout, assis ou couchés. » (v.103)"]'::jsonb,1,'« Allah dit : ﴿ وَمَا خَلَقْتُ الْجِنَّ وَالْإِنسَ إِلَّا لِيَعْبُدُونِ ﴾ « Je n''ai créé les djinns et les hommes que pour qu''ils M''adorent » [Sourate adh-Dhâriyât, v.56] »',8),
   (t,c,'moyenne','Quel hadith, rapporté par ''Umar ibn al-Khattâb, est cité pour rappeler l''obligation de corriger l''intention ?','["« Le dhikr d''Allah est le plus grand. »","« Les actions ne valent que par leurs intentions, et chacun ne sera rétribué que selon son intention. »","« Fais en sorte que ta langue reste toujours humide de l''évocation d''Allah. »","« Celui qui évoque Allah dans l''aisance, Allah se rappellera de lui dans l''adversité. »"]'::jsonb,1,'« إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ، وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى – « Les actions ne valent que par leurs intentions, et chacun ne sera rétribué que selon son intention. » [Rapporté par al-Bukhârî n°1 et Muslim n°1907] »',9),
   (t,c,'moyenne','''Abd ar-Rahmân ibn Mahdî disait : « Celui qui veut écrire un livre, qu''il commence par ce hadith [sur l''intention]. »','["Vrai","Faux"]'::jsonb,0,'« Des savants comme ''Abd ar-Rahmân ibn Mahdî disaient : « Celui qui veut écrire un livre, qu''il commence par ce hadith », afin de réformer son intention dès le départ et de ne viser que la satisfaction d''Allah. »',10),
   (t,c,'moyenne','Que dit al-Fudayl ibn ''Iyâd sur la sincérité ?','["« L''intention est la moitié de l''adoration. »","« Délaisser l''œuvre pour les gens est de l''ostentation, et œuvrer pour les gens est du shirk. Et la sincérité, c''est qu''Allah te préserve des deux. »","« Celui qui œuvre pour les gens est sincère. »","« La sincérité consiste à agir en secret. »"]'::jsonb,1,'« Comme l''a dit al-Fudayl ibn ''Iyâd : « Délaisser l''œuvre pour les gens est de l''ostentation, et œuvrer pour les gens est du shirk. Et la sincérité, c''est qu''Allah te préserve des deux. » »',11),
   (t,c,'moyenne','Le dhikr est une adoration qui demande beaucoup de temps, d''argent et d''efforts physiques.','["Vrai","Faux"]'::jsonb,1,'« Parmi les adorations qu''Allah a prescrites, il y a une adoration facile, qui ne demande ni beaucoup de temps, ni argent, ni grands efforts. Elle peut être accomplie à tout moment et en toute circonstance : il s''agit du dhikr. »',12),
   (t,c,'moyenne','Quel hadith, rapporté par Abû Hurayra, compare une assemblée sans dhikr d''Allah à quelque chose d''impur ?','["« Les assemblées du dhikr sont les assemblées des anges. »","« Il n''est pas un groupe de personnes qui se lève d''une assemblée dans laquelle ils n''ont pas évoqué Allah sans qu''ils se lèvent comme s''ils quittaient la carcasse putréfiée d''un âne. »","« Celui qui évoque Allah dans l''aisance, Allah se rappellera de lui dans l''adversité. »","« Les mufarridûn ont devancé les autres. »"]'::jsonb,1,'« مَا مِنْ قَوْمٍ يَقُومُونَ مِنْ مَجْلِسٍ لَا يَذْكُرُونَ اللَّهَ فِيهِ إِلَّا قَامُوا عَنْ مِثْلِ جِيفَةِ حِمَارٍ – « Il n''est pas un groupe de personnes qui se lève d''une assemblée dans laquelle ils n''ont pas évoqué Allah sans qu''ils se lèvent comme s''ils quittaient la carcasse putréfiée d''un âne. » [Rapporté par Abû Dâwûd n°4855] »',13),
   (t,c,'moyenne','Le verset de la sourate al-Ahzâb (v.35) promet le pardon et une immense récompense à ceux qui invoquent souvent Allah.','["Vrai","Faux"]'::jsonb,0,'« ﴿ وَالذَّاكِرِينَ اللَّهَ كَثِيرًا وَالذَّاكِرَاتِ أَعَدَّ اللَّهُ لَهُم مَّغْفِرَةً وَأَجْرًا عَظِيمًا ﴾ – « Ceux et celles qui invoquent souvent Son nom, à tous ceux-là Allah réserve Son pardon et une immense récompense. » [Sourate al-Ahzâb, v.35] »',14),
   (t,c,'moyenne','Selon le Prophète ﷺ (hadith rapporté par al-Bukhârî n°6407), à quoi ressemble celui qui évoque son Seigneur par rapport à celui qui ne L''évoque pas ?','["À celui qui prie par rapport à celui qui ne prie pas","Au vivant et au mort","Au riche et au pauvre","À l''érudit et à l''ignorant"]'::jsonb,1,'« مَثَلُ الَّذِي يَذْكُرُ رَبَّهُ وَالَّذِي لَا يَذْكُرُ رَبَّهُ مَثَلُ الْحَيِّ وَالْمَيِّتِ – « L''exemple de celui qui évoque son Seigneur et de celui qui ne L''évoque pas est semblable à celui du vivant et du mort. » (Rapporté par al-Bukhârî n°6407) »',15),
   (t,c,'moyenne','Allah a interdit d''être insouciant vis-à-vis de Son évocation dans la sourate al-A''râf (v.205).','["Vrai","Faux"]'::jsonb,0,'« ﴿ وَلَا تَكُن مِّنَ الْغَافِلِينَ ﴾ – « […] sans jamais te laisser distraire. » [Sourate al-A''râf, v.205] »',16),
   (t,c,'moyenne','Un bédouin est venu au Prophète ﷺ en disant que les prescriptions de l''Islam étaient nombreuses pour lui. Quelle réponse le Prophète lui a-t-il donnée ?','["« Accomplis les cinq prières. »","« Fais en sorte que ta langue reste toujours humide de l''évocation et du rappel d''Allah. »","« Lis le Coran chaque jour. »","« Jeûne le mois de Ramadan. »"]'::jsonb,1,'« لَا يَزَالُ لِسَانُكَ رَطْبًا مِنْ ذِكْرِ اللَّهِ – « Fais en sorte que ta langue reste toujours humide de l''évocation et du rappel d''Allah. » [Rapporté par at-Tirmidhî n°3375 et Ibn Mâja n°3793] »',17),
   (t,c,'moyenne','Dans son ouvrage Al-Wâbil as-Sayyib, combien de bienfaits du dhikr Ibn al-Qayyim a-t-il finalement cités ?','["100","99","73","40"]'::jsonb,2,'« L''imam Ibn al-Qayyim رحمه الله explique qu''il a voulu rappeler environ une centaine de bienfaits du dhikr. Il en a finalement cité 73, en appuyant chacun d''eux par des preuves (dalîl) issues du Coran et de la Sunna. »',18),
   (t,c,'moyenne','Parmi les bienfaits du dhikr cités par Ibn al-Qayyim figure le fait qu''il « illumine le cœur et le visage ».','["Vrai","Faux"]'::jsonb,0,'« Parmi ces bienfaits, le cheikh mentionne : Il illumine le cœur et le visage. »',19),
   (t,c,'moyenne','Selon Ibn al-Qayyim, le dhikr occupe la langue et l''éloigne de la médisance et de la calomnie.','["Vrai","Faux"]'::jsonb,0,'« Il occupe la langue et l''éloigne de la médisance et de la calomnie — car se vouer à l''adoration d''Allah nous préserve de la désobéissance à ce qu''Il a interdit. »',20),
   (t,c,'moyenne','En combien de catégories principales Ibn al-Qayyim a-t-il regroupé les preuves coraniques sur l''importance du dhikr ?','["5 catégories","7 catégories","10 catégories","12 catégories"]'::jsonb,2,'« L''imam Ibn al-Qayyim رحمه الله a essayé de regrouper ces preuves en dix catégories principales. »',21),
   (t,c,'moyenne','Quel verset de la sourate al-Jumu''a (v.10) lie la félicité à l''abondance dans l''évocation d''Allah ?','["« Invoquez fréquemment le nom d''Allah. »","« Et évoquez Allah abondamment pour que vous réussissiez. »","« Souvenez-vous de Moi, Je me souviendrai de vous. »","« Et le rappel d''Allah est le plus grand. »"]'::jsonb,1,'« ﴿ وَاذْكُرُوا اللَّهَ كَثِيرًا لَّعَلَّكُمْ تُفْلِحُونَ ﴾ – « Et évoquez Allah abondamment pour que vous réussissiez. » [Sourate al-Jumu''a, v.10] »',22),
   (t,c,'moyenne','La 5e catégorie des textes d''Ibn al-Qayyim montre que délaisser le dhikr, en étant distrait par les biens et les enfants, est une cause de perte (sourate Munafiqûn, v.9).','["Vrai","Faux"]'::jsonb,0,'« Les textes montrant que délaisser l''évocation d''Allah, en étant distrait par autre chose, est une cause de perte : ﴿ يَا أَيُّهَا الَّذِينَ آمَنُوا لَا تُلْهِكُمْ أَمْوَالُكُمْ وَلَا أَوْلَادُكُمْ عَن ذِكْرِ اللَّهِ ﴾ [Sourate Munafiqûn, v.9] »',23),
   (t,c,'moyenne','Quel verset (sourate al-Baqara, v.152) mentionne qu''Allah évoque en retour ceux qui L''évoquent ?','["« Et accomplis la prière pour M''évoquer. »","« Souvenez-vous donc de Moi, Je me souviendrai de vous. »","« Et le rappel d''Allah est le plus grand. »","« Célébrez Sa sainteté matin et soir. »"]'::jsonb,1,'« ﴿ فَٱذْكُرُونِىٓ أَذْكُرْكُمْ ﴾ – « Souvenez-vous donc de Moi, Je me souviendrai de vous. » [Sourate al-Baqara, v.152] »',24),
   (t,c,'moyenne','Le verset « وَلَذِكْرُ اللَّهِ أَكْبَرُ » (Sourate al-''Ankabût, v.45) signifie que « le rappel d''Allah est le plus grand ».','["Vrai","Faux"]'::jsonb,0,'« ﴿ وَلَذِكْرُ اللَّهِ أَكْبَرُ ﴾ – « Et le rappel d''Allah est le plus grand. » [Sourate al-''Ankabût, v.45] »',25),
   (t,c,'moyenne','Quelle est la première des quatre grandes vertus du dhikr citées par le cheikh d''après Ibn al-Qayyim ?','["Le dhikr protège contre Shaytân","L''évocation d''Allah est la meilleure et la plus pure des actions auprès d''Allah","Le dhikr obtient le pardon","Le dhikr fait devancer les autres croyants"]'::jsonb,1,'« 1. L''évocation d''Allah est la meilleure et la plus pure des actions auprès d''Allah. »',26),
   (t,c,'moyenne','Dans le hadith d''Abû ad-Dardâ'' (at-Tirmidhî n°3377), le Prophète ﷺ dit que le dhikr est meilleur que quoi ?','["La prière surérogatoire","Dépenser l''or et l''argent, et rencontrer l''ennemi sur le champ de bataille","Le jeûne volontaire","Le pèlerinage volontaire"]'::jsonb,1,'« أَلَا أُنَبِّئُكُمْ بِخَيْرِ أَعْمَالِكُمْ… خَيْرٍ لَكُمْ مِنْ إِنْفَاقِ الذَّهَبِ وَالْوَرِقِ، وَخَيْرٍ لَكُمْ مِنْ أَنْ تَلْقَوْا عَدُوَّكُمْ فَتَضْرِبُوا أَعْنَاقَهُمْ وَيَضْرِبُوا أَعْنَاقَكُمْ؟… ذِكْرُ اللَّهِ – [Rapporté par at-Tirmidhî n°3377] »',27),
   (t,c,'moyenne','Les mufarridûn, qui ont devancé les autres croyants selon le hadith de Muslim (n°2676), sont ceux qui évoquent Allah abondamment.','["Vrai","Faux"]'::jsonb,0,'« سَبَقَ الْمُفَرِّدُونَ – « Les mufarridûn ont devancé [les autres]. » Ils dirent : « Qui sont les mufarridûn ? » Il dit : الذَّاكِرُونَ اللَّهَ كَثِيرًا وَالذَّاكِرَاتُ – « Ceux qui évoquent Allah abondamment. » (Rapporté par Muslim n°2676) »',28),
   (t,c,'moyenne','Dans le hadith d''Abû ''Ayyâsh az-Zuraqî (Abû Dâwûd n°5077), dire le matin « Lâ ilâha illâ Allâh wahdahu lâ sharîka lah… » apporte combien de bienfaits ?','["3 bienfaits","4 bienfaits","5 bienfaits","7 bienfaits"]'::jsonb,2,'« Dans ce hadith, le Prophète ﷺ a cité cinq bienfaits du dhikr : (1) équivalent à l''affranchissement d''un esclave ; (2) effacement de dix péchés ; (3) inscription de dix bonnes actions ; (4) élévation de dix degrés ; (5) protection contre Shaytân jusqu''au soir. »',29),
   (t,c,'moyenne','Selon le hadith d''Abû ''Ayyâsh az-Zuraqî, la formule « Lâ ilâha illâ Allâh wahdahu… » dite le matin protège contre Shaytân jusqu''au soir.','["Vrai","Faux"]'::jsonb,0,'« وَكَانَ فِي حِرْزٍ مِنَ الشَّيْطَانِ حَتَّى يُمْسِيَ – il est en protection contre Shaytân jusqu''au soir. [Rapporté par Abû Dâwûd n°5077] »',30),
   (t,c,'moyenne','Selon l''imam an-Nawawî dans Al-Adhkâr, quel est le consensus des savants sur le dhikr en état d''impureté majeure (janâba) ?','["Il est interdit en toute circonstance","Il est permis avec le cœur et la langue, à condition de ne pas avoir l''intention de réciter le Coran","Il n''est permis que dans le cœur, pas avec la langue","Il est permis uniquement pour les femmes en période de menstrues"]'::jsonb,1,'« L''imam an-Nawawî rapporte dans son livre Al-Adhkâr qu''il existe un consensus des savants (ijmâ'') sur le fait qu''il est permis à la personne en état de janâba, ainsi qu''à la femme en période de menstrues ou de lochies, de faire le dhikr d''Allah avec le cœur et avec la langue, à condition de ne pas avoir l''intention de réciter le Coran. »',31),
   (t,c,'moyenne','En état d''impureté, il est permis de dire « Innâ lillâhi wa innâ ilayhi râji''ûn » car l''intention est le dhikr et non la récitation du Coran.','["Vrai","Faux"]'::jsonb,0,'« Toutefois, si une personne en état d''impureté majeure ou mineure apprend un malheur, elle peut dire : إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ – Cela est permis, car l''intention est ici de faire le rappel d''Allah et non de réciter le Coran. »',32),
   (t,c,'moyenne','L''invocation « Subhâna alladhî sakhkhara lanâ hâdhâ » peut être prononcée en état d''impureté. Pourquoi ?','["Parce qu''elle ne fait pas partie du Coran","Parce qu''elle est prononcée sous forme de dhikr et non comme récitation coranique","Parce que cette formule est uniquement une invocation de voyage","Parce qu''elle est recommandée uniquement pour les femmes"]'::jsonb,1,'« Bien que cette formule soit un verset du Coran, elle est prononcée ici sous forme de dhikr et non comme récitation coranique. »',33),
   (t,c,'moyenne','Il n''existe aucune divergence entre les savants sur le fait que la meilleure des évocations d''Allah est la récitation du Coran.','["Vrai","Faux"]'::jsonb,0,'« Il n''existe pas de divergence entre les savants sur le fait que la meilleure des évocations d''Allah est la récitation du Coran. »',34),
   (t,c,'moyenne','Durant le rukû'', quelle est la meilleure évocation à prononcer selon le cours ?','["سُبْحَانَ اللَّهِ وَبِحَمْدِهِ","سُبْحَانَ رَبِّيَ الْأَعْلَى","سُبْحَانَ رَبِّيَ الْعَظِيمِ","اللَّهُ أَكْبَرُ"]'::jsonb,2,'« Durant le rukû'' et le sujûd, le meilleur est de prononcer les évocations enseignées par le Prophète ﷺ, comme سُبْحَانَ رَبِّيَ الْعَظِيمِ dans le rukû'' et سُبْحَانَ رَبِّيَ الْأَعْلَى dans le sujûd. »',35),
   (t,c,'moyenne','La récitation du Coran est interdite durant le rukû'' et le sujûd.','["Vrai","Faux"]'::jsonb,0,'« Durant le rukû'' et le sujûd, le meilleur est de prononcer les évocations enseignées par le Prophète ﷺ. La récitation du Coran y est même interdite. »',36),
   (t,c,'moyenne','De façon générale (en dehors de situations particulières), qu''est-ce qui est meilleur : le dhikr ou l''invocation (du''â'') ?','["L''invocation (du''â'') est toujours meilleure","Le dhikr est meilleur que l''invocation","Ils sont équivalents en toute circonstance","Cela dépend uniquement du moment de la journée"]'::jsonb,1,'« De façon générale — en dehors de certaines situations — le dhikr est meilleur que l''invocation (du''â''). »',37),
   (t,c,'moyenne','Quel hadith (al-Bukhârî, Khalq Af''âl al-''Ibâd) justifie que le dhikr est meilleur que le du''â'' ?','["« Les actions ne valent que par leurs intentions. »","« Celui que Mon évocation occupe au détriment de Me demander, Je lui donnerai mieux que ce que Je donne à ceux qui demandent. »","« L''exemple de celui qui évoque son Seigneur est comme le vivant et le mort. »","« Fais en sorte que ta langue reste humide du dhikr d''Allah. »"]'::jsonb,1,'« مَنْ شَغَلَهُ ذِكْرِي عَنْ مَسْأَلَتِي أَعْطَيْتُهُ أَفْضَلَ مَا أُعْطِي السَّائِلِينَ – « Celui que Mon évocation occupe au détriment de Me demander, Je lui donnerai mieux que ce que Je donne à ceux qui demandent. » [Rapporté par al-Bukhârî dans Khalq Af''âl al-''Ibâd ; hadith jugé hasan par Ibn Hajar] »',38),
   (t,c,'moyenne','Toutes les invocations rapportées dans le Coran et la Sunna commencent par des louanges et glorifications d''Allah avant la demande.','["Vrai","Faux"]'::jsonb,0,'« On remarque d''ailleurs que toutes les invocations rapportées dans le Coran et la Sunna commencent par des louanges et glorifications d''Allah avant la demande. C''est la manière la plus complète : louer Allah, se rapprocher de Lui, puis formuler la demande. »',39),
   (t,c,'moyenne','Parmi les comportements (adab) du dhikr, lequel est INCORRECT selon le cours ?','["Le faire avec sincérité et humilité","Le faire à voix haute pour que tout le monde entende","Le faire avec l''esprit, le cœur et la langue","Le faire de préférence en état de purification"]'::jsonb,1,'« Le faire à voix basse, c''est-à-dire qu''on s''entend soi-même, sans crier. »',40),
   (t,c,'moyenne','Il est recommandé, lors du dhikr, de se mettre en direction de la Qibla et de baisser la tête.','["Vrai","Faux"]'::jsonb,0,'« Se mettre en direction de la Qibla, baisser la tête, ne pas regarder à droite et à gauche, ce qui aide à se concentrer. »',41),
   (t,c,'moyenne','Parmi les situations où le dhikr est répréhensible ou interdit, laquelle est citée dans le cours ?','["Lorsqu''on est en voyage","Lorsqu''on est assis pour faire ses besoins","Lorsqu''on est couché avant de dormir","Lorsqu''on marche dans la rue"]'::jsonb,1,'« Lorsqu''on est assis pour faire ses besoins : il est demandé de se taire et de s''empresser afin de revenir rapidement au rappel d''Allah. »',42),
   (t,c,'moyenne','Lorsque l''imâm prononce la khutba, il est demandé d''écouter attentivement et non de faire le dhikr.','["Vrai","Faux"]'::jsonb,0,'« Lorsque l''imâm prononce la khutba : ce qui est demandé est d''écouter attentivement l''imâm, et non de faire le dhikr. »',43),
   (t,c,'moyenne','Selon le cours, lorsqu''on est debout en prière, qu''est-ce qui est demandé en priorité ?','["Faire le dhikr silencieusement","Réciter le Coran (la Fâtiha puis ce que l''on connaît)","Prononcer des invocations personnelles","Rester en silence total"]'::jsonb,1,'« Lorsqu''on est debout en prière : ce qui est demandé est de réciter le Coran (la Fâtiha puis ce que l''on connaît), et non le dhikr — sauf pour celui qui ne connaît rien du Coran. »',44),
   (t,c,'moyenne','Il est permis et recommandé de faire le dhikr d''Allah debout, assis, couché ou en marchant.','["Vrai","Faux"]'::jsonb,0,'« De façon générale, il est permis et recommandé de faire le dhikr d''Allah debout, assis, couché ou en marchant. »',45),
   (t,c,'moyenne','En état de janâba, il est interdit de réciter le Coran même de mémoire.','["Vrai","Faux"]'::jsonb,0,'« En état d''impureté majeure (janâba), il est interdit de réciter le Coran, même de mémoire, comme l''a rapporté ''Alî ibn Abî Tâlib رضي الله عنه : rien n''empêchait le Prophète ﷺ de réciter le Coran sauf l''état de janâba. »',46),
   (t,c,'moyenne','Quel est le dhikr le plus méritoire selon la réponse finale du cours ?','["Les 99 noms d''Allah","Le dhikr du moment : chaque situation possède son évocation spécifique enseignée par le Prophète ﷺ","La récitation du Coran en toute circonstance","Le tasbîh (SubhânAllâh) répété 1000 fois"]'::jsonb,1,'« Le dhikr du moment : chaque situation possède son évocation spécifique enseignée par le Prophète ﷺ. C''est donc le dhikr approprié à l''instant qui est le plus méritoire. »',47),
   (t,c,'moyenne','Sur quels trois piliers repose toute adoration selon la conclusion du cours ?','["La connaissance, la pratique et la patience","L''amour, l''espérance et la crainte","La sincérité, la conformité à la Sunna et la constance","Le cœur, la langue et les membres"]'::jsonb,1,'« Car le dhikr est une adoration, et toute adoration repose sur trois piliers : l''amour, l''espérance et la crainte. »',48),
   (t,c,'moyenne','Le tawâf, le va-et-vient entre as-Safâ et al-Marwa, et la lapidation des stèles ont été institués pour l''évocation d''Allah (hadith rapporté par at-Tirmidhî n°902).','["Vrai","Faux"]'::jsonb,0,'« « Le tawâf autour de la Ka''ba, le va-et-vient entre as-Safâ et al-Marwa, ainsi que la lapidation des stèles n''ont été institués que pour l''évocation d''Allah. » (Rapporté par at-Tirmidhî n°902 et Abû Dâwûd n°1888 ; hadith hasan) »',49),
   (t,c,'moyenne','Quels sont les trois objectifs principaux de ce séminaire sur Husn al-Muslim ?','["Mémoriser, traduire et publier les invocations","Connaître les invocations rapportées du Prophète ﷺ, œuvrer avec elles dans les moments adéquats, et en expliquer le contenu et la signification","Étudier la grammaire arabe, apprendre les hadiths par cœur et écrire un nouveau livre","Connaître la biographie de l''auteur, lire son ouvrage et le traduire en français"]'::jsonb,1,'« Connaître les invocations rapportées du Prophète ﷺ et celles présentes dans le Coran. Œuvrer avec celles-ci, c''est-à-dire les réciter et les dire dans les moments adéquats où il est recommandé de le faire. Expliquer le contenu de ces invocations et leur signification, pour ceux qui le demandent. »',50);
end $$;
