-- Import Hisnul Mouslim cours 2 (révision): 25 questions "Invocations du réveil et de l'habillement" depuis cours2_hin.json.
-- tenant Abou Abdelwahab (qawaid.abouabdelwahab.com). Remplace le contenu de cours 2.
-- À exécuter une seule fois.

do $$ declare t uuid:='6badf254-27a3-4f69-98e3-e67caa917371'; c uuid;
begin
  select id into c from quiz_courses where tenant_id=t and subject='Hisnul Mouslim' and number=2;
  if c is null then
    insert into quiz_courses(tenant_id,subject,number,title,position)
      values (t,'Hisnul Mouslim',2,'Invocations du réveil et de l''habillement',2) returning id into c;
  else
    update quiz_courses set title='Invocations du réveil et de l''habillement' where id=c;
    delete from quiz_questions where course_id=c;
  end if;
  insert into quiz_questions(tenant_id,course_id,difficulte,question,options,correct_index,justification,position) values
   (t,c,'moyenne','Selon Ibn ''Abbâs, Mujâhid et l''imam Ibn as-Salâh, en quoi consiste l''évocation abondante d''Allah mentionnée dans le verset 41 de la sourate al-Ahzâb ?','["Réciter le Coran en entier chaque jour","Se rappeler d''Allah dans les différents moments de la journée : le matin, le soir, avant de dormir, après les prières et dans toutes les situations où le Coran et la Sunna ont encouragé le dhikr","Accomplir les cinq prières obligatoires uniquement","Faire le dhikr uniquement après les prières du fajr et du ''ichâ"]'::jsonb,1,'« Ibn ''Abbâs, Mujâhid et l''imam Ibn as-Salâh expliquaient que cette évocation abondante consiste à se rappeler d''Allah dans les différents moments de la journée : le matin et le soir, avant de dormir, après les prières, ainsi que dans toutes les situations où le Coran et la Sunna ont encouragé le dhikr. »',1),
   (t,c,'moyenne','Selon le cours, le meilleur dhikr de manière générale est la récitation du Coran, mais il existe des situations où les évocations rapportées dans la Sunna sont plus méritoires à ce moment précis.','["Vrai","Faux"]'::jsonb,0,'« De manière générale, le meilleur dhikr est la récitation du Coran, mais il existe certaines situations où les évocations rapportées dans la Sunna sont plus méritoires à ce moment précis. »',2),
   (t,c,'moyenne','Pourquoi l''auteur de Husn al-Muslim commence-t-il son livre par les invocations du réveil ?','["Parce que c''est le chapitre le plus court et le plus simple","Parce qu''il a suivi le déroulement de la journée, qui commence par le réveil","Parce que les invocations du réveil sont les plus méritoires de toutes","Parce que Ibn al-Qayyim lui a conseillé de commencer ainsi"]'::jsonb,1,'« L''auteur a agencé son livre en suivant le déroulement de la journée. Or, la journée commence par le réveil. »',3),
   (t,c,'moyenne','Qui rapporte la première invocation que le Prophète ﷺ prononçait en se mettant dans sa couche : « Bismika Allâhumma amûtu wa ahyâ » ?','["Abû Hurayra رضي الله عنه","''Ubâda ibn as-Sâmit رضي الله عنه","Hudhayfa ibn al-Yamân رضي الله عنه","Anas ibn Mâlik رضي الله عنه"]'::jsonb,2,'« Hudhayfa ibn al-Yamân rapporte que lorsque le Prophète ﷺ se mettait dans sa couche, il disait : بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا »',4),
   (t,c,'moyenne','Pourquoi dit-on dans l''invocation du réveil « qui nous a fait vivre après nous avoir fait mourir » alors qu''on sort du sommeil et non de la mort ?','["C''est une erreur de traduction ; le terme arabe ne signifie pas « mort »","Parce que le sommeil est une petite mort, comme l''ont expliqué les savants","Parce qu''on se réfère à la vie après la mort dans l''au-delà","Parce qu''il s''agit d''une formule purement symbolique sans sens littéral"]'::jsonb,1,'« Parce que le sommeil est une petite mort, comme l''ont expliqué les savants. C''est Allah qui fait dormir et c''est Allah qui permet le réveil. »',5),
   (t,c,'moyenne','Selon le cours, le réveil quotidien rappelle concrètement la résurrection du Jour dernier, de la même manière qu''Allah réveille le dormeur, Il ressuscitera les créatures après leur mort.','["Vrai","Faux"]'::jsonb,0,'« Le réveil quotidien rappelle ainsi la résurrection du Jour dernier. De la même manière qu''Allah réveille le dormeur après son sommeil, Il ressuscitera les créatures après leur mort. »',6),
   (t,c,'moyenne','Quels sont les deux piliers indissociables de l''unicité (tawhîd) selon l''explication du dhikr nocturne dans ce cours ?','["La connaissance et la pratique","La négation de toute divinité en dehors d''Allah et l''affirmation qu''Allah seul mérite l''adoration","La prière et le jeûne","La crainte d''Allah et l''espérance en Sa miséricorde"]'::jsonb,1,'« L''unicité repose sur deux piliers indissociables : La négation : « لَا إِلَهَ إِلَّا اللَّهُ », qui consiste à nier toute divinité digne d''adoration en dehors d''Allah. L''affirmation : « وَحْدَهُ لَا شَرِيكَ لَهُ », qui consiste à affirmer qu''Allah est le Seul à mériter l''adoration, sans aucun associé. »',7),
   (t,c,'moyenne','Quelles sont les quatre paroles les plus aimées d''Allah, citées dans le hadith rapporté par Muslim (n°2137) ?','["Bismillâh, al-hamdulillâh, lâ ilâha illallâh et Allâhu akbar","Subhânallâh, al-hamdulillâh, lâ ilâha illallâh et Allâhu akbar","Astaghfirullâh, subhânallâh, al-hamdulillâh et lâ ilâha illallâh","Lâ hawla wa lâ quwwata, subhânallâh, al-hamdulillâh et Allâhu akbar"]'::jsonb,1,'« أَحَبُّ الْكَلَامِ إِلَى اللَّهِ أَرْبَعٌ: سُبْحَانَ اللَّهِ، وَالْحَمْدُ لِلَّهِ، وَلَا إِلَهَ إِلَّا اللَّهُ، وَاللَّهُ أَكْبَرُ، لَا يَضُرُّكَ بِأَيِّهِنَّ بَدَأْتَ — « Les paroles les plus aimées d''Allah sont au nombre de quatre : Subḥâna-Llâh, al-ḥamdu li-Llâh, lâ ilâha illa-Llâh et Allâhu akbar. Peu importe par laquelle on commence. » [Rapporté par Muslim, n° 2137] »',8),
   (t,c,'moyenne','Que signifie « Lâ hawla wa lâ quwwata illâ billâh » selon l''explication du cours ?','["Il n''y a pas de création ni de puissance si ce n''est celle d''Allah","Il n''y a ni changement de situation, ni force, ni capacité à accomplir le bien ou à délaisser le mal, si ce n''est par l''aide d''Allah","Il n''y a pas de pardon ni de miséricorde en dehors d''Allah","Il n''y a pas de richesse ni de subsistance en dehors d''Allah"]'::jsonb,1,'« Cette parole exprime la dépendance totale du serviteur envers son Seigneur. Il n''y a ni changement de situation, ni force, ni capacité à accomplir le bien ou à délaisser le mal, si ce n''est par l''aide d''Allah, al-''Aliyy al-''Aẓîm (Le Très-Haut, l''Immense). »',9),
   (t,c,'moyenne','Selon le hadith du dhikr nocturne, si l''on se réveille la nuit et qu''on prononce l''invocation de ''Ubâda ibn as-Sâmit, puis qu''on accomplit les ablutions et qu''on prie, cette prière est acceptée.','["Vrai","Faux"]'::jsonb,0,'« S''il accomplit ensuite ses ablutions puis prie deux unités de prière, sa prière est acceptée, car il l''accomplit après avoir commencé sa journée par le rappel et l''évocation d''Allah. »',10),
   (t,c,'moyenne','Quelle est la règle pratique pour distinguer le dhikr du réveil à prononcer selon l''heure ?','["On prononce toujours le dhikr de ''Ubâda, quelle que soit l''heure","Si on se réveille pour le fajr sans se rendormir : dhikr du matin ; si on se réveille la nuit avec l''intention de se rendormir : dhikr de ''Ubâda ibn as-Sâmit","On prononce uniquement le dhikr du matin pour tous les réveils","On prononce uniquement « Bismillâh » pour tout réveil nocturne"]'::jsonb,1,'« Si je me réveille le matin pour la prière du fajr sans me rendormir, je prononce le dhikr du matin : « الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ ». Si je me réveille dans la nuit avec l''intention de me rendormir, je fais le dhikr rapporté de ''Ubâda ibn as-Sâmit. »',11),
   (t,c,'moyenne','Selon le hadith d''Abû Hurayra (Bukhârî n°1142 et Muslim n°776), combien de nœuds Shaytân noue-t-il sur la nuque de celui qui dort ?','["Un nœud","Deux nœuds","Trois nœuds","Sept nœuds"]'::jsonb,2,'« يَعْقِدُ الشَّيْطَانُ عَلَى قَافِيَةِ رَأْسِ أَحَدِكُمْ إِذَا هُوَ نَامَ ثَلَاثَ عُقَدٍ — « Shaytân fait trois nœuds sur la nuque de l''un de vous lorsqu''il dort. » [Hadith d''Abû Hurayra, rapporté par Al-Bukhârî n°1142 et Muslim ibn al-Hajjâj n°776] »',12),
   (t,c,'moyenne','Selon le hadith sur les nœuds de Shaytân, dans quel ordre les nœuds se défont-ils ?','["Prière → ablutions → dhikr","Dhikr → prière → ablutions","Dhikr → ablutions → prière","Ablutions → dhikr → prière"]'::jsonb,2,'« فَإِنِ اسْتَيْقَظَ فَذَكَرَ اللَّهَ انْحَلَّتْ عُقْدَةٌ، فَإِنْ تَوَضَّأَ انْحَلَّتْ عُقْدَةٌ، فَإِنْ صَلَّى انْحَلَّتْ عُقَدُهُ كُلُّهَا — S''il se réveille et évoque Allah, un nœud se défait ; s''il fait les ablutions, un autre se défait ; et s''il prie, tous les nœuds se défont. »',13),
   (t,c,'moyenne','Selon le hadith rapporté par Al-Bukhârî (n°3295) et Muslim (n°238), Shaytân passe la nuit dans les narines de l''être humain, c''est pourquoi il est recommandé de se moucher trois fois au réveil.','["Vrai","Faux"]'::jsonb,0,'« Il convient également d''accomplir les ablutions et d''inspirer puis rejeter l''eau par le nez trois fois, car le Prophète ﷺ a indiqué que Shayṭân passe la nuit dans les narines de l''être humain : « فَإِنَّ الشَّيْطَانَ يَبِيتُ عَلَى خَيْشُومِهِ ». [Rapporté par Al-Bukhârî n°3295 et Muslim ibn al-Hajjâj n°238] »',14),
   (t,c,'moyenne','Qui a passé la nuit chez Maymûna bint al-Hârith et observé le Prophète ﷺ réciter les derniers versets de la sourate Âl ''Imrân à son réveil nocturne (Bukhârî n°183) ?','["Abû Bakr as-Siddîq رضي الله عنه","''Abd Allâh ibn ''Abbâs رضي الله عنه","Hudhayfa ibn al-Yamân رضي الله عنه","''Ubâda ibn as-Sâmit رضي الله عنه"]'::jsonb,1,'« Cela a été rapporté par ''Abd Allâh ibn ''Abbâs : il a passé la nuit chez Maymûna bint al-Hârith, qui est sa tante maternelle… Le Prophète ﷺ a discuté avec son épouse, puis a dormi. Lorsqu''est arrivé le dernier tiers de la nuit, il s''est levé, a levé les yeux vers le ciel et a récité ces versets. [Rapporté par Al-Bukhârî n°183 et Muslim ibn al-Hajjâj n°763] »',15),
   (t,c,'moyenne','Les cinq types de lien de l''âme avec le corps selon Ibn al-Qayyim incluent : le lien dans le ventre de la mère, dans la vie d''ici-bas, durant le sommeil, dans le barzakh, et après la résurrection.','["Vrai","Faux"]'::jsonb,0,'« Les cinq types de lien de l''âme avec le corps (selon Ibn al-Qayyim) : Le lien de l''âme avec le corps du fœtus, dans le ventre de sa mère. Le lien de l''âme avec le corps dans la vie de ce bas monde. Le lien de l''âme avec le corps durant le sommeil. Le lien de l''âme avec le corps dans le barzakh. Le lien de l''âme avec le corps après la résurrection, pour le jugement et la rétribution. »',16),
   (t,c,'moyenne','Que comprend la louange (al-hamd) selon l''explication du cours ?','["Uniquement remercier Allah pour Ses bienfaits","L''éloge d''Allah pour Ses bienfaits et Sa perfection, avec amour, vénération et glorification","Réciter al-Fâtiha à voix haute","Dire « al-hamdulillâh » cent fois par jour"]'::jsonb,1,'« La louange consiste à faire l''éloge d''Allah pour Ses bienfaits et pour Sa perfection, avec amour, vénération et glorification. Une louange ne peut être complète sans ces éléments. »',17),
   (t,c,'moyenne','Selon le hadith cité dans le chapitre de l''habillement (jugé hassan par Al-Albânî), que reçoit celui qui met un vêtement et dit « al-hamdulillâhi alladhî kasânî hâdhâ ath-thawba wa razaqanîhi min ghayri hawlin minnî wa lâ quwwa » ?','["Dix bonnes actions inscrites et dix péchés effacés","Le pardon de ses péchés passés","Une protection contre Shaytân jusqu''au soir","La récompense équivalente à l''affranchissement d''un esclave"]'::jsonb,1,'« celui qui met un vêtement et dit : « الْحَمْدُ لِلَّهِ الَّذِي كَسَانِي هَذَا الثَّوْبَ وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ » on lui pardonnera ses péchés passés. »',18),
   (t,c,'moyenne','Dans le hadith qudsî rapporté par Muslim ibn al-Hajjâj, Allah dit : « Ô Mes serviteurs ! Vous êtes tous nus sauf celui que J''ai habillé ; demandez-Moi de vous vêtir, Je vous vêtirai. »','["Vrai","Faux"]'::jsonb,0,'« Et dans le hadith qudsî rapporté par Muslim ibn al-Hajjâj, Allah dit : « يَا عِبَادِي، كُلُّكُمْ عَارٍ إِلَّا مَنْ كَسَوْتُهُ، فَاسْتَكْسُونِي أَكْسُكُمْ » — « Ô Mes serviteurs ! Vous êtes tous nus sauf celui que J''ai habillé ; demandez-Moi de vous vêtir, Je vous vêtirai. » »',19),
   (t,c,'moyenne','Quels sont les trois points à retenir avant et lors de l''habillement selon le cours ?','["Faire les ablutions, réciter la Fâtiha, puis s''habiller","Dire « Bismillâh », faire les louanges d''Allah pour le vêtement en le nommant, et s''en remettre totalement à Allah en reconnaissant sa dépendance envers Lui","Mettre le vêtement en commençant par le côté droit, dire « al-hamdulillâh », puis demander protection","Réciter une invocation, faire deux prosternations de gratitude, puis s''habiller"]'::jsonb,1,'« 1. Avant d''enfiler le vêtement, il est recommandé de dire « Bismillâh ». 2. Faire les louanges d''Allah pour ce bienfait — ce vêtement (jilbâb, khimâr, niqâb, qamîs, sarwâl, chaussures…) — en le nommant et en reconnaissant qu''il provient de Lui. 3. S''en remettre totalement à Allah et se rappeler le besoin du serviteur envers Lui. »',20),
   (t,c,'moyenne','Selon le hadith rapporté par Al-Bukhârî (n°5787), porter un vêtement en dessous des chevilles constitue une cause d''entrée en Enfer.','["Vrai","Faux"]'::jsonb,0,'« مَا أَسْفَلَ مِنَ الْكَعْبَيْنِ فَفِي النَّارِ — « Ce qui est en dessous des chevilles ira en Enfer. » [Hadith de Abû Hurayra, rapporté par Al-Bukhârî n°5787] »',21),
   (t,c,'moyenne','Selon le hadith rapporté par at-Tirmidhî (n°606) selon ''Alî ibn Abî Tâlib, comment le croyant se protège-t-il de la vision des djinns lorsqu''il retire ses vêtements ?','["En récitant le verset du Trône (Âyat al-Kursî)","En disant « A''ûdhu billâhi min ash-shaytâni r-rajîm »","En disant « Bismillâh »","En se couvrant rapidement avec un autre vêtement"]'::jsonb,2,'« Dans un hadith rapporté par at-Tirmidhî (n°606) selon ''Alî ibn Abî Tâlib. Le Prophète ﷺ a indiqué que la protection entre la vision des djinns et les parties intimes de l''homme, lorsqu''il enlève ses vêtements, c''est de dire « Bismillâh ». »',22),
   (t,c,'moyenne','Selon le cours, dans quelles situations dit-on « Bismillâh » en enlevant son vêtement ?','["Uniquement aux toilettes","Uniquement en se changeant le soir","Lorsqu''on descend son vêtement pour faire ses besoins, lorsqu''on retire son vêtement chez soi ou lorsqu''on change de tenue","Uniquement lors de la douche obligatoire (ghusl)"]'::jsonb,2,'« Lorsqu''on descend son vêtement pour faire ses besoins (aux toilettes ou en s''isolant à l''extérieur) ; lorsqu''on retire son vêtement chez soi (par exemple en rentrant du travail pour prendre sa douche) ; ou lorsqu''on change de tenue. »',23),
   (t,c,'moyenne','Concernant le « Bismillâh » aux toilettes, quel est l''avis le plus sûr à retenir selon le cours ?','["Le prononcer à voix haute en entrant","Ne jamais le prononcer dans les toilettes","Le prononcer dans le cœur uniquement","Le prononcer avant d''entrer dans les toilettes"]'::jsonb,3,'« D''autres recommandent de le prononcer avant d''entrer, et c''est l''avis le plus sûr à retenir. »',24),
   (t,c,'moyenne','Selon le cours, faire une invocation pour son frère musulman lorsqu''il porte un vêtement neuf réjouit le cœur, renforce les liens et concrétise l''amour entre les musulmans, conformément au hadith d''Anas ibn Mâlik (Bukhârî n°13).','["Vrai","Faux"]'::jsonb,0,'« Cela réjouit le cœur, renforce les liens et concrétise l''amour entre les musulmans, conformément à la parole du Prophète ﷺ : « لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ » — « Aucun de vous ne sera véritablement croyant jusqu''à ce qu''il aime pour son frère ce qu''il aime pour lui-même. » [Hadith d''Anas ibn Mâlik, rapporté par Al-Bukhârî n°13 et Muslim ibn al-Hajjâj n°45] »',25);
end $$;
