-- Import Hisnul Mouslim cours 3 (révision): 25 questions "Mérites du dhikr et invocations des actes quotidiens" depuis cours3.json.
-- tenant Abou Abdelwahab (qawaid.abouabdelwahab.com). Remplace le contenu de cours 3.
-- À exécuter une seule fois.

do $$ declare t uuid:='6badf254-27a3-4f69-98e3-e67caa917371'; c uuid;
begin
  select id into c from quiz_courses where tenant_id=t and subject='Hisnul Mouslim' and number=3;
  if c is null then
    insert into quiz_courses(tenant_id,subject,number,title,position)
      values (t,'Hisnul Mouslim',3,'Mérites du dhikr et invocations des actes quotidiens',3) returning id into c;
  else
    update quiz_courses set title='Mérites du dhikr et invocations des actes quotidiens' where id=c;
    delete from quiz_questions where course_id=c;
  end if;
  insert into quiz_questions(tenant_id,course_id,difficulte,question,options,correct_index,justification,position) values
   (t,c,'moyenne','Dans le hadith d''Abû ad-Dardâ'' (at-Tirmidhî n°3377), le Prophète ﷺ présente le dhikr comme meilleur que deux choses. Lesquelles ?','["Le jeûne volontaire et le pèlerinage","Dépenser l''or et l''argent, et rencontrer l''ennemi au combat en se frappant mutuellement le cou","La prière de la nuit et le jeûne du lundi et jeudi","La lecture du Coran et la prière surérogatoire"]'::jsonb,1,'« Voulez-vous que je vous informe de la meilleure de vos œuvres… meilleure pour vous que de dépenser l''or et l''argent, et meilleure que de rencontrer votre ennemi au combat et de vous frapper mutuellement le cou ? … L''évocation d''Allah. » [Rapporté par at-Tirmidhî n°3377 et Ibn Mâjah n°3790 ; authentifié par al-Albânî]',1),
   (t,c,'moyenne','Selon le cours, le dhikr est une cause de protection, d''élévation en degrés, d''expiation des péchés et d''obtention des récompenses.','["Vrai","Faux"]'::jsonb,0,'« Le dhikr est une cause de protection, d''élévation en degrés, d''expiation des péchés et d''obtention des récompenses. Plus le serviteur multiplie l''évocation d''Allah, plus son cœur se purifie et se rapproche de son Seigneur. »',2),
   (t,c,'moyenne','Quel hadith rapporté par al-Bukhârî (n°6312) est cité comme invocation du réveil le matin ?','["« Bismika Allâhumma amûtu wa ahyâ »","« Al-hamdu li-Llâhi alladhî ahyânâ ba''da mâ amâtanâ wa ilayhi an-nushûr »","« Lâ ilâha illâ Llâh wahdahu lâ sharîka lah »","« Subhâna-Llâhi wa bi hamdih »"]'::jsonb,1,'« Et lorsqu''il se réveillait, il disait : « الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ » — « Louange à Allah qui nous a fait revivre après nous avoir fait mourir, et c''est vers Lui qu''est la résurrection. » [Rapporté par al-Bukhârî n°6312] »',3),
   (t,c,'moyenne','Selon le cours, l''invocation du réveil rappelle deux bienfaits : le fait qu''Allah ait permis au serviteur de se réveiller, et le rappel de la future résurrection.','["Vrai","Faux"]'::jsonb,0,'« Cette invocation rappelle ainsi deux immenses bienfaits : (1) le fait qu''Allah ait permis au serviteur de se réveiller après son sommeil, (2) et le rappel de la future résurrection. »',4),
   (t,c,'moyenne','Comment les savants appellent-ils le sommeil selon ce cours ?','["La grande mort (al-mawt al-akbar)","La petite mort (al-mawt al-asghar)","Le repos de l''âme (râhat ar-rûh)","L''absence temporaire (al-ghayba al-waqtiyya)"]'::jsonb,1,'« Le sommeil est appelé par les savants « la petite mort » (al-mawt al-asghar). En effet, durant le sommeil, Allah reprend les âmes puis les renvoie lorsqu''Il veut le réveil du serviteur. »',5),
   (t,c,'moyenne','Que dit-on avant d''entrer aux toilettes selon la Sunna du Prophète ﷺ ?','["« Allâhumma innî a''ûdhu bika mina-l-khabâ''ith » uniquement","« Bismillâh, Allâhumma innî a''ûdhu bika mina-l-khubthi wa-l-khabâ''ith »","« A''ûdhu billâhi min ash-shaytâni r-rajîm »","« Bismillâh ar-Rahmân ar-Rahîm »"]'::jsonb,1,'« Avant d''entrer aux toilettes, le Prophète ﷺ disait : "Bismillâh, Allâhumma innî a''ûdhu bika mina-l-khubthi wa-l-khabâ''ith" »',6),
   (t,c,'moyenne','Selon le cours, si la personne est déjà dans les toilettes, elle doit dire « Bismillâh » à voix haute pour se protéger des djinns.','["Vrai","Faux"]'::jsonb,1,'« Bismillah : le Cheikh explique qu''il convient de dire « Bismillah » dans le cœur si la personne est déjà dans les toilettes, car il est déconseillé de prononcer le nom d''Allah dans cet endroit. »',7),
   (t,c,'moyenne','Quelle invocation le Prophète ﷺ prononçait-il en sortant des toilettes, et pourquoi selon certains savants ?','["« Al-hamdulillâh » — pour remercier Allah d''avoir facilité ce besoin","« Ghufrânaka » — pour demander pardon à Allah après un moment où le dhikr était délaissé","« Bismillâh » — pour se purifier en citant le nom d''Allah","« Astaghfirullâh » — car les toilettes sont un lieu d''impureté"]'::jsonb,1,'« En sortant des toilettes, le Prophète ﷺ disait : "Ghufrânaka". Certains savants expliquent que le Prophète ﷺ prononçait cette invocation pour demander pardon à Allah après un moment où le dhikr était délaissé dans les toilettes. »',8),
   (t,c,'moyenne','Selon le cours, il est permis de répondre au salâm dans les toilettes.','["Vrai","Faux"]'::jsonb,1,'« Ne pas parler dans les toilettes, même pour répondre au salâm. »',9),
   (t,c,'moyenne','Concernant le statut juridique du « Bismillâh » avant les ablutions, quel est l''avis des hanbalites et d''al-Albânî ?','["C''est une sunna recommandée, sans être obligatoire","C''est une obligation, et les ablutions ne sont pas complètes sans mention du nom d''Allah","C''est une obligation uniquement pour celui qui s''en souvient ; en cas d''oubli, les ablutions restent valides","C''est permis mais pas nécessaire"]'::jsonb,1,'« Avis 2 (hanbalites et al-Albânî) : il s''agit d''une obligation, et les ablutions ne sont pas complètes sans mention du nom d''Allah. »',10),
   (t,c,'moyenne','Quel est l''avis de la majorité des savants sur le « Bismillâh » avant les ablutions en cas d''oubli ?','["Les ablutions sont invalidées et doivent être refaites","C''est une sunna, donc l''oubli ne pose aucun problème","C''est une obligation pour celui qui s''en souvient ; en cas d''oubli, les ablutions restent valides","Il faut dire « Bismillâh » à la fin des ablutions pour compenser"]'::jsonb,2,'« Avis 3 (majorité des savants) : c''est une obligation pour celui qui s''en souvient ; en cas d''oubli, les ablutions restent valides, mais il convient de dire « Bismillah » dès que cela est rappelé. »',11),
   (t,c,'moyenne','Selon le hadith de ''Uqba ibn ''Amir (Muslim n°234), que reçoit celui qui fait parfaitement ses ablutions puis prononce la shahada ?','["Le pardon de ses péchés passés et à venir","Les huit portes du Paradis lui sont ouvertes et il entre par celle qu''il souhaite","Dix bonnes actions inscrites et dix péchés effacés","Une protection contre Shaytân jusqu''au soir"]'::jsonb,1,'« Celui qui fait ses ablutions de manière parfaite puis prononce : "Ashhadu an lâ ilâha illâ Llâh wahdahu lâ sharîka lah, wa ashhadu anna Muhammadan ''abduhu wa rasûluh." les huit portes du Paradis lui sont ouvertes, et il entre par celle qu''il souhaite. » [Rapporté par Muslim n°234] »',12),
   (t,c,'moyenne','Selon le cours, les invocations à la fin des ablutions montrent que les ablutions ne sont pas uniquement une purification extérieure par l''eau, mais qu''elles sont complétées par une purification intérieure par l''unicité d''Allah.','["Vrai","Faux"]'::jsonb,0,'« Cela montre que les ablutions ne sont pas uniquement une purification extérieure par l''eau, mais qu''elles sont complétées par une purification intérieure par l''unicité d''Allah et le témoignage de la foi. »',13),
   (t,c,'moyenne','Selon les savants cités dans le cours, les invocations à la fin des ablutions sont obligatoires ; les ablutions sont invalides sans elles.','["Vrai","Faux"]'::jsonb,1,'« Ces invocations sont recommandées (sunna) et non obligatoires. Les ablutions restent valides même si elles ne sont pas prononcées. »',14),
   (t,c,'moyenne','Quelle est l''invocation à dire en sortant de chez soi, selon le hadith d''Anas ibn Mâlik (Abû Dâwûd, authentifié par al-Albânî) ?','["« Allâhumma innî a''ûdhu bika an adhilla aw udhall »","« Bismillâh, tawakkaltu ''ala Llâh, wa lâ hawla wa lâ quwwata illâ bi-Llâh »","« Al-hamdu li-Llâhi alladhî ahyânâ ba''da mâ amâtanâ »","« Bismillâh walajna wa bismillâh kharajnâ »"]'::jsonb,1,'« Lorsque l''homme sort de chez lui et dit : "Au nom d''Allah, je place ma confiance en Allah, et il n''y a de force ni de puissance qu''en Allah"… il lui est alors dit : "Tu as été guidé, on t''a suffi et on t''a protégé", et les démons s''éloignent de lui. » [Rapporté par Abû Dâwûd et at-Tirmidhî, authentifié par al-Albânî] »',15),
   (t,c,'moyenne','Selon le cours, que signifie le tawakkul dans l''invocation de sortie de la maison ?','["Ne prendre aucune cause matérielle et attendre qu''Allah agisse seul","Placer sa confiance totale en Allah tout en prenant les causes légiférées et en agissant avec sérieux","Réciter des versets du Coran avant toute action","Demander l''aide des autres musulmans avant d''entreprendre quoi que ce soit"]'::jsonb,1,'« Le tawakkul consiste à placer sa confiance totale en Allah, tout en prenant les causes légiférées et en agissant avec sérieux. »',16),
   (t,c,'moyenne','Quel hadith est rapporté par Umm Salama رضي الله عنها sur l''invocation que le Prophète ﷺ prononçait en sortant de chez lui ?','["Il levait les yeux vers le ciel et demandait à Allah de le protéger de l''égarement, du fait de trébucher, de l''injustice et de l''ignorance","Il disait « Bismillâh » et se taisait ensuite jusqu''à destination","Il récitait l''Âyat al-Kursî puis sortait sans rien ajouter","Il disait « Al-hamdulillâh » en levant les mains vers le ciel"]'::jsonb,0,'« Le Prophète ﷺ ne sortait jamais de chez lui sans lever son regard vers le ciel et dire : "Ô Allah, je cherche refuge auprès de Toi contre le fait de m''égarer ou d''être égaré, de trébucher ou de faire trébucher, d''être injuste ou de subir l''injustice, d''ignorer ou d''être traité avec ignorance." » [Rapporté par Abû Dâwûd, authentifié par al-Albânî] »',17),
   (t,c,'moyenne','Selon le cours, il est recommandé en entrant chez soi de commencer par le pied droit, et en sortant par le pied gauche — sauf pour les toilettes où la règle est inversée.','["Vrai","Faux"]'::jsonb,0,'« en commençant par le pied droit pour l''entrée et en sortant avec le pied gauche, sauf pour les toilettes où la règle est inversée. »',18),
   (t,c,'moyenne','Que dit le cours sur l''écoute d''un cours religieux ou du Coran dans les toilettes ?','["C''est permis car l''intention est bonne","Ce n''est pas permis dans les toilettes ; dans la salle de bain c''est non interdit mais déconseillé","C''est permis partout tant que le volume est bas","C''est obligatoire d''écouter le Coran même aux toilettes pour garder le cœur en éveil"]'::jsonb,1,'« Dans les toilettes, cela n''est pas permis, car il s''agit d''un lieu d''impureté où il ne convient pas d''y évoquer Allah ni d''y écouter le Coran ou un rappel religieux. Dans la salle de bain, cela n''est pas interdit mais reste déconseillé. »',19),
   (t,c,'moyenne','Que faut-il faire si les toilettes sont orientées vers la Qibla ?','["Cela est permis en intérieur uniquement, car la règle ne s''applique qu''en extérieur","Il est interdit en toute circonstance ; il convient de se décaler légèrement ou de modifier l''orientation si possible","Il suffit de détourner le regard pour que cela soit valide","Cela est autorisé car le Coran ne mentionne pas cette interdiction explicitement"]'::jsonb,1,'« Il est interdit de se diriger vers la Qibla en faisant ses besoins, que ce soit en intérieur ou en extérieur. Si les toilettes sont déjà orientées dans cette direction, il convient de se décaler légèrement afin d''éviter d''être directement face à la Qibla, ou de modifier leur orientation si cela est possible. »',20),
   (t,c,'moyenne','Selon le cours, si l''on oublie de dire l''invocation en sortant de chez soi, il est possible de la prononcer dès qu''on s''en souvient, dans les escaliers ou le couloir par exemple.','["Vrai","Faux"]'::jsonb,0,'« Si elles sont oubliées, il est permis de les dire dès que l''on s''en souvient, tant que l''on n''est pas dans un endroit inapproprié comme les toilettes. Par exemple, si l''on oublie de les dire en sortant, il est possible de les prononcer dans les escaliers, dans le couloir, ou juste après avoir quitté la maison. »',21),
   (t,c,'moyenne','Quelle est la règle de base concernant la langue des invocations selon le cours ?','["Les invocations peuvent être dites dans n''importe quelle langue dès le départ","La règle de base est de les dire en arabe ; si elles ne sont pas maîtrisées, on peut les lire depuis un support ou les dire temporairement en français le temps de les apprendre","Il est obligatoire de les mémoriser en arabe avant de les utiliser","Les invocations doivent toujours être dites en arabe sans exception"]'::jsonb,1,'« La règle de base est que les invocations sont dites en arabe… Si elles ne sont pas encore maîtrisées, il est possible de les lire depuis un livre ou un support écrit, le temps de les apprendre. Et si la personne ne sait pas lire l''arabe, elle peut les dire en français temporairement. »',22),
   (t,c,'moyenne','Selon le cours, dire « Bismillâh ar-Rahmân ar-Rahîm » est valable et constitue une forme plus complète que simplement dire « Bismillâh ».','["Vrai","Faux"]'::jsonb,0,'« Dire simplement « Bismillah » est suffisant, et ajouter « ar-Rahman ar-Rahim » est également valable et constitue une forme plus complète pour celui qui le souhaite. Les deux formulations sont rapportées dans l''usage et restent dans le cadre de la Sunna. »',23),
   (t,c,'moyenne','Selon la conclusion du cours, quelle est la recommandation pratique principale concernant l''apprentissage des invocations ?','["Tout mémoriser en une seule fois avant de les utiliser","Commencer par les invocations les plus importantes et les plus fréquentes, apprendre progressivement et comprendre leur sens","Utiliser uniquement les traductions françaises pour mieux comprendre","Se concentrer uniquement sur l''invocation du réveil et du coucher"]'::jsonb,1,'« Il est plutôt conseillé de commencer par les invocations les plus importantes et les plus fréquentes, comme celles du matin, du soir, ou de l''entrée et la sortie de la maison. L''apprentissage doit se faire progressivement… L''essentiel est aussi de comprendre le sens des paroles, car cela permet au cœur d''être حاضر et de vivre réellement le dhikr. »',24),
   (t,c,'moyenne','Selon le cours, même une petite quantité de dhikr faite régulièrement a un impact immense, et la constance est plus importante que la quantité.','["Vrai","Faux"]'::jsonb,0,'« surtout d''être constant, car même une petite quantité de dhikr, faite régulièrement, a un impact immense. »',25);
end $$;
